apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: hdd-bucket
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Retain
parameters:
  objectStoreName: hdd-object-store
  objectStoreNamespace: rook-ceph