---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: hdd-pool-replica
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 2
    requireSafeReplicaSize: false
  deviceClass: hdd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-replica
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  clusterID: rook-ceph
  pool: hdd-pool-replica
  imageFormat: "2"
  imageFeatures: layering

# Delete the rbd volume when a PVC is deleted
reclaimPolicy: Retain
allowVolumeExpansion: true