---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: nvme-pool-unsafe
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 1
    requireSafeReplicaSize: false
  deviceClass: nvme
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-unsafe
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  clusterID: rook-ceph
  pool: nvme-pool-unsafe
  imageFormat: "2"
  imageFeatures: layering

# Delete the rbd volume when a PVC is deleted
reclaimPolicy: Retain
allowVolumeExpansion: true