apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 10m
  chart:
    spec:
      chart: garage
      path: ./script/helm/garage
      version: 0.9.2 
      sourceRef:
        kind: GitRepository  # Changed from HelmRepository
        name: garage-charts
        namespace: flux-system
  values:
    persistence:
      meta:
        existingClaim: garage-meta
      data:
        existingClaim: garage-data
    deploy:
      replicaCount: 1
    garage:
      replicationFactor: 1
    
